### ISSUE TITLE
billing address

### ISSUE THREAD

**Issue by catorghans** [circleinteractive/uk.co.circleinteractive.payment.sagepay#12]
Is it right that the CiviCRM Billing address is not used as Billing Address to Sagepay?

**Comment by andy-walker** [comment]
Hi there,

Are you saying "is it right?" as in "am I right in thinking this?" - if so, you are right in thinking that.

If you're saying "is it right?" as in "is this the best way to handle it?", then yes, we think so, on balance - and have given it a fair bit of thought.

I think the majority of end users don't want to make the distinction / they already have the user's address on the system / don't want them to have to enter it again, it would require having to set up an address profile of the type Billing rather than use the built in one - so I think, on balance, doing that by default creates more problems that it solves.

But if you do really need it to do that, you can create the following value in the civicrm_setting table:

group_name: uk.co.circleinteractive.payment.sagepay 
name: use_billing
value: s:1:"1";

And it will use the Billing address instead.

Hope that helps,

Andy
